### ISSUE TITLE
use osx on travis-ci?

### ISSUE THREAD

**Issue by AlJohri** [thoughtbot/laptop#494]
I'm curious why you don't currently try actually running the mac script on travis?

**Comment by AlJohri** [comment]
nevermind, just tried this myself and that didn't seem like it was ever going to end

**Comment by AlJohri** [comment]
reopening this. I got it working in 24 minutes for my fork of laptop which does a bunch more stuff. https://travis-ci.org/WPMedia/laptop/builds/245425407

here is a travis ci config that works:

```
language: generic
os: osx
osx_image: xcode8.3

install:
  - brew install shellcheck

script:
  - shellcheck mac -e SC2039
  - ./mac

matrix:
  fast_finish: true

notifications:
  email: false
```

The only change I needed to make was adding sudo to the chsh command and appending "$USER" at the end of it.
